[package]
name = "ctci"
version = "0.1.0"
authors = ["Pablo Ortiz <po26@duke.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.*"